name: Android Release Build

on:
  workflow_dispatch: # This makes the workflow runnable manually from the GitHub Actions UI
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'main'

jobs:
  build_android_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3' # Or flutter-version-file: pubspec.yaml

      - name: Display Flutter Version
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      # --- Signing setup ---
      - name: Decode Keystore File
        run: echo "${{ secrets.ANDROID_UPLOAD_KEYSTORE }}" | base64 --decode > android/app/release-key.jks

      - name: Create Keystore Properties File
        run: |
          echo "storeFile=release-key.jks" > android/key.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties

      - name: Build Android APK (Release)
        run: flutter build apk --release --split-per-abi

      - name: Show APK Version Info
        run: |
          AaptPath=$(ls ${ANDROID_HOME}/build-tools/*/aapt | sort -V | tail -n 1)
          echo "Using aapt from: $AaptPath"

          for apk in build/app/outputs/flutter-apk/*.apk; do
            echo ""
            echo "APK: $apk"
            $AaptPath dump badging "$apk" | grep versionCode
          done

      - name: Upload Android APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/apk/release/
